# -*- coding: utf-8 -*-
"""协议薄壳：复用 groundTest/ano_protocol.py，不重写。

groundTest 不是包（无 __init__.py），用 sys.path 注入方式 import，
后续若 groundTest 改造为包，此处只需删掉 sys.path 注入。
"""
from __future__ import annotations
import os
import sys

# 把 <repo>/groundTest 加入 sys.path
_GROUNDTEST_DIR = os.path.normpath(
    os.path.join(os.path.dirname(__file__), os.pardir, os.pardir, "groundTest")
)
if _GROUNDTEST_DIR not in sys.path:
    sys.path.insert(0, _GROUNDTEST_DIR)

# 透传 ano_protocol 全部公共符号
from ano_protocol import (  # noqa: E402  (path 注入后再 import)
    FRAME_HEAD,
    ADDR_BROADCAST,
    ADDR_UPPER,
    ADDR_IMU,
    ADDR_FC_STM32,
    AUTO_CMD_ABORT_LAND,
    AUTO_CMD_CLEAR_ERROR,
    AUTO_CMD_DRYRUN_TAKEOFF_LAND,
    AUTO_CMD_EMERGENCY_LOCK,
    AUTO_CMD_PRECHECK,
    AUTO_CMD_QUERY_STATUS,
    AUTO_CMD_LOCK_RC,
    AUTO_CMD_LAND_ONLY,
    AUTO_CMD_RELEASE_RC,
    AUTO_CMD_REQUEST_MODE2,
    AUTO_CMD_START_LOW_TAKEOFF_LAND,
    AUTO_CMD_TAKEOFF_HOLD,
    AUTO_FLAG_NO_XY_MOTION,
    AUTO_MOVE_AXIS_AUTO,
    AUTO_MOVE_AXIS_X,
    AUTO_MOVE_AXIS_XY,
    AUTO_MOVE_AXIS_XYZ,
    AUTO_MOVE_AXIS_Y,
    AUTO_MOVE_AXIS_Z,
    AUTO_MOVE_CMD_QUERY,
    AUTO_MOVE_CMD_START,
    AUTO_MOVE_CMD_STOP,
    AUTO_MOVE_LIMIT_CM,
    AUTO_VEL_CMD_QUERY,
    AUTO_VEL_CMD_SET,
    AUTO_VEL_CMD_STOP,
    AUTO_VEL_LIMIT_CMPS,
    AUTO_YAW_LIMIT_DPS,
    AUTO_PROTOCOL_VER,
    AUTO_SAFETY_KEY,
    AUTO_STATUS_FLAG_RC_HOLD_FRAME,
    AUTO_STATUS_FLAG_VOLT_LOW,
    AUTO_STATUS_FLAG_VOLT_TAKEOFF_OK,
    AUTO_STATUS_FLAG_VOLT_WARN,
    AutoStatus,
    CMD_AUTO_MISSION,
    CMD_AUTO_MOVE,
    CMD_AUTO_VELOCITY,
    CMD_AUTO_STATUS,
    COLOR_BLACK,
    COLOR_RED,
    COLOR_GREEN,
    Frame,
    FrameParser,
    build_f7_auto_cmd,
    build_f9_move_cmd,
    build_fa_velocity_cmd,
    build_frame,
    build_f1_xy,
    build_f2_param,
    build_f3_xyz,
    calc_checksum,
    hex_dump,
    parse_f8_auto_status,
)

CMD_RPI_POSITION_MIRROR = 0xF6

__all__ = [
    "FRAME_HEAD",
    "ADDR_BROADCAST",
    "ADDR_UPPER",
    "ADDR_IMU",
    "ADDR_FC_STM32",
    "AUTO_CMD_ABORT_LAND",
    "AUTO_CMD_CLEAR_ERROR",
    "AUTO_CMD_DRYRUN_TAKEOFF_LAND",
    "AUTO_CMD_EMERGENCY_LOCK",
    "AUTO_CMD_PRECHECK",
    "AUTO_CMD_QUERY_STATUS",
    "AUTO_CMD_LOCK_RC",
    "AUTO_CMD_LAND_ONLY",
    "AUTO_CMD_RELEASE_RC",
    "AUTO_CMD_REQUEST_MODE2",
    "AUTO_CMD_START_LOW_TAKEOFF_LAND",
    "AUTO_CMD_TAKEOFF_HOLD",
    "AUTO_FLAG_NO_XY_MOTION",
    "AUTO_MOVE_AXIS_AUTO",
    "AUTO_MOVE_AXIS_X",
    "AUTO_MOVE_AXIS_XY",
    "AUTO_MOVE_AXIS_XYZ",
    "AUTO_MOVE_AXIS_Y",
    "AUTO_MOVE_AXIS_Z",
    "AUTO_MOVE_CMD_QUERY",
    "AUTO_MOVE_CMD_START",
    "AUTO_MOVE_CMD_STOP",
    "AUTO_MOVE_LIMIT_CM",
    "AUTO_VEL_CMD_QUERY",
    "AUTO_VEL_CMD_SET",
    "AUTO_VEL_CMD_STOP",
    "AUTO_VEL_LIMIT_CMPS",
    "AUTO_YAW_LIMIT_DPS",
    "AUTO_PROTOCOL_VER",
    "AUTO_SAFETY_KEY",
    "AUTO_STATUS_FLAG_RC_HOLD_FRAME",
    "AUTO_STATUS_FLAG_VOLT_LOW",
    "AUTO_STATUS_FLAG_VOLT_TAKEOFF_OK",
    "AUTO_STATUS_FLAG_VOLT_WARN",
    "AutoStatus",
    "CMD_AUTO_MISSION",
    "CMD_AUTO_MOVE",
    "CMD_AUTO_VELOCITY",
    "CMD_AUTO_STATUS",
    "COLOR_BLACK",
    "COLOR_RED",
    "COLOR_GREEN",
    "Frame",
    "FrameParser",
    "build_f7_auto_cmd",
    "build_f9_move_cmd",
    "build_fa_velocity_cmd",
    "build_frame",
    "build_f1_xy",
    "build_f2_param",
    "build_f3_xyz",
    "calc_checksum",
    "hex_dump",
    "parse_f8_auto_status",
    "CMD_RPI_POSITION_MIRROR",
]
